### ISSUE TITLE
Error with Pantheon/JLA likelihood and pandas

### ISSUE THREAD

**Issue by Pavsters** [brinckmann/montepython_public#111]
Hello! 
I accidentally posted this again in the previous version repository so I thought it best to close that issue and post here instead. I am very new to montepython, so any advice would be greatly appreciated!
I wanted to run a test run of the pantheon likelihood, so I edited the input/jla.param file to change the likelihood to pantheon, and was asked to install pandas with pip3, and so I did, pandas version 1.0.1.

Afterwards, I ran a very simple chain:

python montepython/Montepython.py run -p input/jla.param -o pantheon_test/ -N 10
and I get this error:
Running Monte Python v3.3.2
with CLASS v2.9.0
Testing likelihoods for:
->JLA
Traceback (most recent call last):
File "montepython/MontePython.py", line 40, in
sys.exit(run())
File "/home/pav/montepython/montepython/run.py", line 32, in run
custom_command)
File "/home/pav/montepython/montepython/run.py", line 191, in safe_initialisation
cosmo, data, command_line, success = initialise(custom_command)
File "/home/pav/montepython/montepython/initialise.py", line 67, in initialise
data = Data(command_line, path)
File "/home/pav/montepython/montepython/data.py", line 356, in init
self.initialise_likelihoods(self.experiments)
File "/home/pav/montepython/montepython/data.py", line 485, in initialise_likelihoods
elem, elem, folder, elem))
File "", line 1, in
File "/home/pav/montepython/montepython/likelihoods/Pantheon/init.py", line 64, in init
self.C00 = self.read_matrix(self.mag_covmat_file)
File "/home/pav/montepython/montepython/likelihood_class.py", line 2500, in read_matrix
matrix = read_table(path).as_matrix().reshape((length, length))
File "/home/pav/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 5274, in getattr
return object.getattribute(self, name)
AttributeError: 'DataFrame' object has no attribute 'as_matrix'

This was replicated when I switched back to JLA. Is this a compatibility issue with the version of pandas? If so which version should I be using? Thank you in advance.

**Comment by MarisolJC** [comment]
Hi!

I was having the same problem, I'm using python 3.7.4 and I was using pandas version 1.0.1 but now I installed pandas 0.24.0 and it works for me. Try to install it, maybe it solves your problem too...

**Comment by Pavsters** [comment]
> Hi!
> 
> I had the same error message, I'm using python 3.7.4 and I was using pandas version 1.0.1 but I installed pandas 0.24.0 and it works for me. Try to install it, maybe it solves your problem too...

Thank you, worked like a charm! I am closing the issue.
