### ISSUE TITLE
Issue with 'Planck_lowl_EE' likelihood for LCDM + iso-curvature 

### ISSUE THREAD

**Issue by subhajitghosh-phy** [brinckmann/montepython_public#121]
I am trying to reproduce Planck 2018 isocurvature results using CLASS & MontePython. 
FYI, I am following 1807.06211 & 1502.02114, using 'two scale' parametrization given in those papers, modified CLASS accordingly ( implemented Eq. 136 of 1502.02114).

I am getting a 'clik' error:
----------------------------------------------------------------------------------------------------------------------------------
Running Monte Python v3.3.2

with CLASS v2.9.0

Testing likelihoods for:
 ->Planck_lowl_EE

Initializing SimAll
----
clik version 3be036bbb4f9
  simall simall_EE_BB_TE
Checking likelihood '/user1/subhajit/cosmo-class/plc-2018/plc_3.0/plc-3.01/../../../baseline/plc_3.0/low_l/simall/simall_100x143_offlike5_EE_Aplanck_B.clik' on test data. got -197.99 expected -197.99 (diff -4.1778e-08)
----
Creating error/2020-04-17_1000000__1.txt

Deduced starting covariance matrix:
['omega_b', 'omega_cdm', '100*theta_s', 'tau_reio', 'P_{RR}^1', 'P_{RR}^2', 'P_{II}^1', 'P_{II}^2', 'P_{RI}^1', 'A_planck']
[[2.25e-04 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 1.69e-06 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 9.00e-08 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 6.40e-05 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.00e-20 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.00e-20 0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.00e-20 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.00e-20 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.00e-20 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 6.25e-06]]
Update routine is enabled with value 50 (recommended: 50)
This number is rescaled by cycle length 14 (N_slow + f_fast * N_fast) to 700
Traceback (most recent call last):
  File "../../montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/user1/subhajit/cosmo-class/montepython_public/montepython/run.py", line 45, in run
    sampler.run(cosmo, data, command_line)
  File "/user1/subhajit/cosmo-class/montepython_public/montepython/sampler.py", line 46, in run
    mcmc.chain(cosmo, data, command_line)
  File "/user1/subhajit/cosmo-class/montepython_public/montepython/mcmc.py", line 474, in chain
    loglike = sampler.compute_lkl(cosmo, data)
  File "/user1/subhajit/cosmo-class/montepython_public/montepython/sampler.py", line 776, in compute_lkl
    value = likelihood.loglkl(cosmo, data)
  File "/user1/subhajit/cosmo-class/montepython_public/montepython/likelihood_class.py", line 1051, in loglkl
    lkl = self.clik(tot)[0]
  File "lkl.pyx", line 89, in clik.lkl.clik.__call__
clik.lkl.CError: <exception str() failed>
----------------------------------------------------------------------------------------------------------------------------------

This error is only appearing for 'Planck_lowl_EE' and for a specific set of values of the isocurvature parameters. 

The .param file I have used for the above run starts the chain with those values -- therefore the error occurs in the beginning. If I do not start the chain with those values -- the code runs fine until it reaches those values and gives out the same error and stops.

Other Planck 2018 likelihoods are not having any issues -- I have checked.

I want to emphasis that there is no issue with CLASS for those parameters. CLASS runs fine and gives the output spectrum. Those parameters are also valid, by which I mean that they fall within the prior range of 1502.02114.

Therefore, it is a problem with 'clik' for 'Planck_lowl_EE'. 

Can someone please help me with this?

I have attached the log.param. I am running this for NIV - neutrino velocity isocurvature. But this problem also occurs for CDI and NDI.

[log.param.txt](https://github.com/brinckmann/montepython_public/files/4492860/log.param.txt)

 ----
Subhajit

**Comment by subhajitghosh-phy** [comment]
An update on the issue:

I just ran the same code on a different cluster. I got this error message which is same as above but has additional info towards the end:

Traceback (most recent call last):
  File "../../../montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/user1/subhajit/flock/cosmo-class/montepython_public/montepython/run.py", line 45, in run
    sampler.run(cosmo, data, command_line)
  File "/user1/subhajit/flock/cosmo-class/montepython_public/montepython/sampler.py", line 46, in run
    mcmc.chain(cosmo, data, command_line)
  File "/user1/subhajit/flock/cosmo-class/montepython_public/montepython/mcmc.py", line 474, in chain
    loglike = sampler.compute_lkl(cosmo, data)
  File "/user1/subhajit/flock/cosmo-class/montepython_public/montepython/sampler.py", line 776, in compute_lkl
    value = likelihood.loglkl(cosmo, data)
  File "/user1/subhajit/flock/cosmo-class/montepython_public/montepython/likelihood_class.py", line 1051, in loglkl
    lkl = self.clik(tot)[0]
  File "lkl.pyx", line 89, in clik.lkl.clik.__call__
clik.lkl.CError: clik_compute(../src/clik.c:391)::ForwardError
  distribution_lkl(../src/minipmc/distribution.c:219)::ForwardError
    lklbs_lkl(../src/lklbs.c:219)::ForwardError
      simall_lkl(../src/simall/clik_simall.c:48)::Error -1233 (multipole EE 2 too large (got 0.501403 expected <0.3))


"Error -1233 (multipole EE 2 too large (got 0.501403 expected <0.3))" -- How can it be fixed?

**Comment by brinckmann** [comment]
Hi Subhajit,

From the second error message it sounds like your CLASS modification returns an unrealistically large value for the ell=2 EE multipole, at least one not covered in the Planck lowl EE likelihood. You'll have to try to think of a way to get around this that biases your results the least, assuming there's not a bug in the code returning these large values.

E.g. three ways I could think to do this:
* You can add a small segment of code in MontePython to reject all points where the value of the ell=2 multipole is too large. However, this would mean parts of parameter space where this is true would be ruled out, which may be too strong a statement.
* Or maybe you can find a way to change the minimum ell in the Planck lowl EE likelihood (i.e. disregard that multipole, assuming the next multipole is fine).
* Another option is maybe you can hardcode an upper limit for the ell=2 multipole. I'm going to guess that 0.3 is already strongly disfavored, so it might be that it wouldn't strongly bias the results if you fix your ell=2 multipole to this value (or slightly smaller) in cases where it's larger. 

You'll have to use your own judgement to guess which option is best or to come up with a different way to get around the problem. Maybe an idea is contacting Planck people to try to find out why there's an upper limit hardcoded in the Planck lowl EE likelihood, which might give you a clue as to its importance.

Best,
Thejs

**Comment by subhajitghosh-phy** [comment]
Dear Thejs,

Thank you so much for addressing this issue and for the suggestions. 

I will start with the 3rd one which seems very reasonable and probably will biases the results the least. 
But before that, I also want to find out regarding the reason for hard coding the limit.

Thanks again.

Best,
Subhajit
