### ISSUE TITLE
CosmoHammer not working

### ISSUE THREAD

**Issue by alessiospuriomancini** [brinckmann/montepython_public#142]
Hi, 

1. In the CosmoHammer interface with MP `cosmo_hammer.py` , the lines

```
from cosmoHammer.likelihood.chain.LikelihoodComputationChain import (
    LikelihoodComputationChain)
from cosmoHammer.sampler.CosmoHammerSampler import CosmoHammerSampler

```

need to be changed into 

```
from cosmoHammer import LikelihoodComputationChain
from cosmoHammer import CosmoHammerSampler

```
as already noted in [https://github.com/baudren/montepython_public/issues/47](url) and [https://github.com/baudren/montepython_public/issues/105](url).

2. In addition, running e.g. 

```
python3 ./montepython_public/montepython/MontePython.py run \
-p ./montepython_public/input/test.param \
-o ./montepython_public/chains/prova \
--conf ./montepython_public/default.conf \
-m CH 

```
 I get

```
Running Monte Python v3.3.4

with CLASS v2.9.3

Testing likelihoods for:
 ->hst, timedelay, test_nuisance1, test_nuisance2

Sampler: <class 'cosmoHammer.CosmoHammerSampler.CosmoHammerSampler'>
configuration: 
  Params: [2.249 0.703 0.1   0.1  ]
  Burnin iterations: 10
  Samples iterations: 30
  Walkers ratio: 50
  Reusing burn in: False
  init pos generator: SampleBallPositionGenerator
  stop criteria: IterationStopCriteriaStrategy
  storage util: SampleFileUtil
likelihoodComputationChain: 
Core Modules: 
  Data
  Class
Likelihood Modules: 
  hst
  timedelay
  test_nuisance1
  test_nuisance2

start burn in
Traceback (most recent call last):
  File "/cluster/project2/cosmo_generation/montepython_public/montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/cluster/project2/cosmo_generation/montepython_public/montepython/run.py", line 45, in run
    sampler.run(cosmo, data, command_line)
  File "/cluster/project2/cosmo_generation/montepython_public/montepython/sampler.py", line 56, in run
    hammer.run(cosmo, data, command_line)
  File "/cluster/project2/cosmo_generation/montepython_public/montepython/cosmo_hammer.py", line 147, in run
    sampler_hammer.startSampling()
  File "/cluster/project2/cosmo_generation/SPS/tens-env/lib/python3.6/site-packages/cosmoHammer/CosmoHammerSampler.py", line 153, in startSampling
    pos, prob, rstate, datas = self.startSampleBurnin()
  File "/cluster/project2/cosmo_generation/SPS/tens-env/lib/python3.6/site-packages/cosmoHammer/CosmoHammerSampler.py", line 206, in startSampleBurnin
    pos, prob, rstate, data = self.sampleBurnin(p0)
  File "/cluster/project2/cosmo_generation/SPS/tens-env/lib/python3.6/site-packages/cosmoHammer/CosmoHammerSampler.py", line 233, in sampleBurnin
    for pos, prob, rstate, datas in self._sampler.sample(p0, iterations=self.burninIterations):
  File "/cluster/project2/cosmo_generation/SPS/tens-env/lib/python3.6/site-packages/emcee/ensemble.py", line 322, in sample
    self.backend.grow(iterations, state.blobs)
  File "/cluster/project2/cosmo_generation/SPS/tens-env/lib/python3.6/site-packages/emcee/backends/backend.py", line 180, in grow
    dt = np.dtype((blobs[0].dtype, blobs[0].shape))
AttributeError: 'dict' object has no attribute 'dtype'
Traceback (most recent call last):
  File "classy.pyx", line 204, in classy.Class.struct_cleanup
TypeError: argument of type 'NoneType' is not iterable
Exception ignored in: 'classy.Class.__dealloc__'
Traceback (most recent call last):
  File "classy.pyx", line 204, in classy.Class.struct_cleanup
TypeError: argument of type 'NoneType' is not iterable

```

running `emcee v. 3.0.2` and `CosmoHammer v0.6.1`. What is this due to?

**Comment by brinckmann** [comment]
Hi Alessio,

Thanks for reminding me of those bugfixes!

I've never tried to run MontePython with emcee v3, but it would be interesting if we could get it working. These lines seem to indicate the problem:
```
  File "/cluster/project2/cosmo_generation/SPS/tens-env/lib/python3.6/site-packages/emcee/backends/backend.py", line 180, in grow
    dt = np.dtype((blobs[0].dtype, blobs[0].shape))
AttributeError: 'dict' object has no attribute 'dtype'
```
Which seems to be a problem within emcee. Maybe it's being called incorrectly by MontePython/CosmoHammer or has been set up incorrectly. Can you check if you can run emcee alone, without going through MontePython? The next step would be to figure out if we need to change something in MontePython or CosmoHammer to get it to work with emcee v3.

Best,
Thejs

**Comment by alessiospuriomancini** [comment]
Hi Thejs,

Thanks for your prompt reply!
It is definitely something to do with the latest versions of `emcee` and `CosmoHammer` and how they are called in MP, as I think it is suggested [here](https://github.com/dfm/emcee/issues/256) too in @sibirrer 's comment.

In answer to your question: yes, I can safely run the tests suggested in the [emcee installation page](https://emcee.readthedocs.io/en/stable/user/install/#test-the-installation)

**Comment by alessiospuriomancini** [comment]
I should add that if I install `emcee v2.2.1` while still using Python 3 I find myself in the same situation described [here](https://github.com/dfm/emcee/issues/287): 

```
Traceback (most recent call last):
  File "/cluster/project2/cosmo_generation/montepython_public/montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/cluster/project2/cosmo_generation/montepython_public/montepython/run.py", line 45, in run
    sampler.run(cosmo, data, command_line)
  File "/cluster/project2/cosmo_generation/montepython_public/montepython/sampler.py", line 56, in run
    hammer.run(cosmo, data, command_line)
  File "/cluster/project2/cosmo_generation/montepython_public/montepython/cosmo_hammer.py", line 147, in run
    sampler_hammer.startSampling()
  File "/cluster/project2/cosmo_generation/SPS/tens-env/lib/python3.6/site-packages/cosmoHammer-0.6.1-py3.6.egg/cosmoHammer/CosmoHammerSampler.py", line 149, in startSampling
  File "/cluster/project2/cosmo_generation/SPS/tens-env/lib/python3.6/site-packages/cosmoHammer-0.6.1-py3.6.egg/cosmoHammer/CosmoHammerSampler.py", line 202, in startSampleBurnin
  File "/cluster/project2/cosmo_generation/SPS/tens-env/lib/python3.6/site-packages/cosmoHammer-0.6.1-py3.6.egg/cosmoHammer/CosmoHammerSampler.py", line 229, in sampleBurnin
  File "/cluster/project2/cosmo_generation/SPS/tens-env/lib/python3.6/site-packages/emcee-2.2.1-py3.6.egg/emcee/ensemble.py", line 198, in sample
  File "/cluster/project2/cosmo_generation/SPS/tens-env/lib/python3.6/site-packages/emcee-2.2.1-py3.6.egg/emcee/ensemble.py", line 382, in _get_lnprob
  File "/cluster/project2/cosmo_generation/SPS/tens-env/lib/python3.6/site-packages/emcee-2.2.1-py3.6.egg/emcee/interruptible_pool.py", line 94, in map
  File "/share/apps/python-3.6.9/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/share/apps/python-3.6.9/lib/python3.6/multiprocessing/pool.py", line 424, in _handle_tasks
    put(task)
  File "/share/apps/python-3.6.9/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/share/apps/python-3.6.9/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot serialize '_io.TextIOWrapper' object

```
