### ISSUE TITLE
Problem in using sdss_lrgDR7 likelihood

### ISSUE THREAD

**Issue by Antara-Dey** [brinckmann/montepython_public#195]
Dear all,
              I am new to the code. I am trying to use montepython_public-3.4 version with sdss_lrgDR7 data and I am getting this following error. I could not understand how to resolve it. Thanks in advance.

Traceback (most recent call last):
  File "montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/home/isipamu2/class_montepython/montepython_public-3.4/montepython/run.py", line 45, in run
    sampler.run(cosmo, data, command_line)
  File "/home/isipamu2/class_montepython/montepython_public-3.4/montepython/sampler.py", line 46, in run
    mcmc.chain(cosmo, data, command_line)
  File "/home/isipamu2/class_montepython/montepython_public-3.4/montepython/mcmc.py", line 787, in chain
    newloglike = sampler.compute_lkl(cosmo, data)
  File "/home/isipamu2/class_montepython/montepython_public-3.4/montepython/sampler.py", line 776, in compute_lkl
    value = likelihood.loglkl(cosmo, data)
  File "/home/isipamu2/class_montepython/montepython_public-3.4/montepython/likelihood_class.py", line 2090, in loglkl
    Psmooth_nl = self.remove_bao(kh,Pnl)
  File "/home/isipamu2/class_montepython/montepython_public-3.4/montepython/likelihood_class.py", line 2327, in remove_bao
    wtrend = scipy.interpolate.UnivariateSpline(wzeros, fwiggle(wzeros), k=3, s=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy/interpolate/fitpack2.py", line 186, in __init__
    xe=bbox[1], s=s)
dfitpack.error: (m>k) failed for hidden m: fpcurf0:m=1

**Comment by brinckmann** [comment]
It appears the scipy interpolation method on line 2327 fails (this is within the remove_bao function starting on line 2300 in montepython/likelihood_class.py), but that is likely a symptom of another problem. Specifically, [this page](https://stackoverflow.com/questions/32230362/python-interpolate-univariatespline-package-error-mk-failed-for-hidden-m) seems to discuss the error that's returned from the interpolation method. As far as I understand it's because the input to the method are 1-length arrays, which obviously can't be interpolated.

Something must be going wrong in a prior computation to make the interpolation function input wzeros, fwiggle(wzeros) length 1 (which they obviously shouldn't be). Most likely a Py3-Py2 compatibility issue, either within the remove_bao function or in the computations prior to remove_bao being called on line 2090. Note it's also called on the preceding line 2089 for the linear power spectrum, which does not seem to return an error, that might be relevant to finding the bug. The remove_bao function is also called on lines 2379 and 2380, so the issue might replicate itself there if the bug is not within the remove_bao function, but is rather in the preceding parts.

Are you using Python 3? I doubt this function and likelihood has been debugged for Python 3, so we should check that there's no Python version compatibility issues and if there is then how we fix them. This seems the most likely source of the error, as I have not encountered it using Python 2 (for which it was written).

Best,
Thejs

**Comment by Antara-Dey** [comment]
Hi Thejs,
             Thanks for your response. We are using python 2.7 version and montepython_public-3.4 version and still gett
