### ISSUE TITLE
The file 'f' does not exist when running montepython

### ISSUE THREAD

**Issue by PhyPy-Dm** [brinckmann/montepython_public#206]
Hi all：
       what's wrong with my montepython when I run " python montepython/MontePython.py -o planck/ -p input/base.param -c covmat/base.covmat -bf bestfit/base.bestfit --conf my.conf  " and getting the follwing errors, how can I fix it?

 /!\ Defaulting to the 'run' command. Please update the call of MontePython. For
     more info, see the help string and/or the documentation

Configuration Error:
 /|\   argument -b/--bestfit: The file 'f' does not exist

Traceback (most recent call last):
  File "/home/hejiayin/anaconda3/lib/python3.8/argparse.py", line 2422, in _get_value
    result = type_func(arg_string)
  File "/home/hejiayin/MCMClass/montepython/montepython/parser_mp.py", line 120, in existing_file
    raise ap.ArgumentTypeError(msg)
argparse.ArgumentTypeError: The file 'f' does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hejiayin/anaconda3/lib/python3.8/argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/hejiayin/anaconda3/lib/python3.8/argparse.py", line 2006, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/home/hejiayin/anaconda3/lib/python3.8/argparse.py", line 1946, in consume_optional
    take_action(action, args, option_string)
  File "/home/hejiayin/anaconda3/lib/python3.8/argparse.py", line 1858, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/home/hejiayin/anaconda3/lib/python3.8/argparse.py", line 2389, in _get_values
    value = self._get_value(action, arg_string)
  File "/home/hejiayin/anaconda3/lib/python3.8/argparse.py", line 2428, in _get_value
    raise ArgumentError(action, msg)
argparse.ArgumentError: argument -b/--bestfit: The file 'f' does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hejiayin/MCMClass/montepython/montepython/run.py", line 191, in safe_initialisation
    cosmo, data, command_line, success = initialise(custom_command)
  File "/home/hejiayin/MCMClass/montepython/montepython/initialise.py", line 31, in initialise
    command_line = parser_mp.parse(custom_command)
  File "/home/hejiayin/MCMClass/montepython/montepython/parser_mp.py", line 1053, in parse
    args = parser.safe_parse_args()
  File "/home/hejiayin/MCMClass/montepython/montepython/parser_mp.py", line 47, in safe_parse_args
    return self.parse_args(args)
  File "/home/hejiayin/anaconda3/lib/python3.8/argparse.py", line 1768, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/home/hejiayin/anaconda3/lib/python3.8/argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/hejiayin/anaconda3/lib/python3.8/argparse.py", line 1988, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/home/hejiayin/anaconda3/lib/python3.8/argparse.py", line 1965, in consume_positionals
    take_action(action, args)
  File "/home/hejiayin/anaconda3/lib/python3.8/argparse.py", line 1874, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/hejiayin/anaconda3/lib/python3.8/argparse.py", line 1159, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/home/hejiayin/anaconda3/lib/python3.8/argparse.py", line 1807, in parse_known_args
    self.error(str(err))
  File "/home/hejiayin/MCMClass/montepython/montepython/parser_mp.py", line 37, in error
    raise io_mp.ConfigurationError(message)
io_mp.ConfigurationError: 

Configuration Error:
 /|\   argument -b/--bestfit: The file 'f' does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/home/hejiayin/MCMClass/montepython/montepython/run.py", line 31, in run
    cosmo, data, command_line, success = safe_initialisation(
  File "/home/hejiayin/MCMClass/montepython/montepython/run.py", line 197, in safe_initialisation
    raise io_mp.ConfigurationError(
io_mp.ConfigurationError: 

Configuration Error:
 /|\   The initialisation was not successful, resulting in a potentially half
/_o_\  created `log.param`. Please see the above error message. If you run the
       exact same command, it will not work. You should solve the problem, and
       try again.

**Comment by lesgourg** [comment]
Dear @PhyPy-Dm , you typed '''-bf bestfit/base.bestfit''' instead of '''-b bestfit/base.bestfit'''  :-)

**Comment by PhyPy-Dm** [comment]
@lesgourg when i typed **-b bestfit/base.bestfit** there's also errors as followed

`/!\ Defaulting to the 'run' command. Please update the call of MontePython. For
     more info, see the help string and/or the documentation
Running Monte Python v3.4.0

with CLASS v3.0.1

Testing likelihoods for:
 ->Planck_highl, Planck_lowl, lowlike



Configuration Error:
 /|\   Trying to import the Planck_highl likelihood as asked in the parameter
/_o_\  file, and failed. Please make sure it is in the `montepython/likelihoods`
       folder, and is a proper python module. Check also that the name of the
       class defined in the __init__.py matches the name of the folder. In case
       this is not enough, here is the original message: No module named
       'likelihoods.Planck_highl'

Traceback (most recent call last):
  File "/home/hejiayin/MCMClass/montepython/montepython/data.py", line 474, in initialise_likelihoods
    exec("from likelihoods.%s import %s" % (
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'likelihoods.Planck_highl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hejiayin/MCMClass/montepython/montepython/run.py", line 191, in safe_initialisation
    cosmo, data, command_line, success = initialise(custom_command)
  File "/home/hejiayin/MCMClass/montepython/montepython/initialise.py", line 67, in initialise
    data = Data(command_line, path)
  File "/home/hejiayin/MCMClass/montepython/montepython/data.py", line 356, in __init__
    self.initialise_likelihoods(self.experiments)
  File "/home/hejiayin/MCMClass/montepython/montepython/data.py", line 477, in initialise_likelihoods
    raise io_mp.ConfigurationError(
io_mp.ConfigurationError: 

Configuration Error:
 /|\   Trying to import the Planck_highl likelihood as asked in the parameter
/_o_\  file, and failed. Please make sure it is in the `montepython/likelihoods`
       folder, and is a proper python module. Check also that the name of the
       class defined in the __init__.py matches the name of the folder. In case
       this is not enough, here is the original message: No module named
       'likelihoods.Planck_highl'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/home/hejiayin/MCMClass/montepython/montepython/run.py", line 31, in run
    cosmo, data, command_line, success = safe_initialisation(
  File "/home/hejiayin/MCMClass/montepython/montepython/run.py", line 197, in safe_initialisation
    raise io_mp.ConfigurationError(
io_mp.ConfigurationError: 

Configuration Error:
 /|\   The initialisation was not successful, resulting in a potentially half
/_o_\  created `log.param`. Please see the above error message. If you run the
       exact same command, it will not work. You should solve the problem, and
       try again.
`

**Comment by PhyPy-Dm** [comment]
@lesgourg  I check the source folder likelihoods of montepython and I didn't find the Planck_highl, Planck_lowl, and I didn't find them in brinckmann's source files on github either.

**Comment by dchooper** [comment]
Hi,

The base.param is a deprecated parameter file that is kept for historical reasons. We recommend instead using one of the base2015... or base2018... param files.

However, you are correct that in it's current implementation it does not run, as it references the likelihoods with the former naming convention (before the release of Planck 2018). We will update this in the forthcoming release such that this param file is operational again. 

Please note also that it is good praxis to specifically pass the "run" command to MontePython (i.e. `python montepython/MontePython.py run`, instead of letting MontePython guess if you are running in run or info mode.

Best,
Deanna

**Comment by PhyPy-Dm** [comment]
Dear @lesgourg when I modify my base.param to change Planck_highl, Planck_lowl to Planck15_highl, Planck15_lowl, which exsit in likelihoods folder, but i get errors again

**/!\ Defaulting to the 'run' command. Please update the call of MontePython. For
     more info, see the help string and/or the documentation
Running Monte Python v3.4.0

with CLASS v3.0.1
 /!\ Detecting empty folder, logging the parameter file

Testing likelihoods for:
 ->Planck15_highl, Planck15_lowl, lowlike

Traceback (most recent call last):
  File "/home/hejiayin/MCMClass/montepython/montepython/likelihood_class.py", line 892, in __init__
    self.clik = clik.clik(self.path_clik)
  File "lkl.pyx", line 72, in clik.lkl.clik.__init__
clik.lkl.CError: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/home/hejiayin/MCMClass/montepython/montepython/run.py", line 31, in run
    cosmo, data, command_line, success = safe_initialisation(
  File "/home/hejiayin/MCMClass/montepython/montepython/run.py", line 191, in safe_initialisation
    cosmo, data, command_line, success = initialise(custom_command)
  File "/home/hejiayin/MCMClass/montepython/montepython/initialise.py", line 67, in initialise
    data = Data(command_line, path)
  File "/home/hejiayin/MCMClass/montepython/montepython/data.py", line 356, in __init__
    self.initialise_likelihoods(self.experiments)
  File "/home/hejiayin/MCMClass/montepython/montepython/data.py", line 491, in initialise_likelihoods
    exec("self.lkl['%s'] = %s('%s/%s.data',\
  File "<string>", line 1, in <module>
  File "/home/hejiayin/MCMClass/montepython/montepython/likelihood_class.py", line 895, in __init__
    raise io_mp.LikelihoodError(
io_mp.LikelihoodError: 

Likelihood Error:
 /|\   The path to the .clik file for the likelihood Planck15_highl was not
/_o_\  found where indicated:
       /home/hejiayin/MCMClass/code/plc_3.0/plc-3.01/../plc_2.0/hi_l/plik/plik_d
       x11dr2_HM_v18_TT.clik
       Note that the default path to search for it is one directory above the
       path['clik'] field. You can change this behaviour in all the
       Planck_something.data, to reflect your local configuration, or
       alternatively, move your .clik files to this place.
**

**Comment by PhyPy-Dm** [comment]
@lesgourg @dchooper Thank you so much, now I know how to solve this problem.

Best,
PhyPy-Dm

**Comment by msabogal** [comment]
Dear @PhyPy-Dm 

How did you solve that problem with the Planck15_highl? 

Best, 
Miguel
