### ISSUE TITLE
example plot

### ISSUE THREAD

**Issue by mubecks** [brinckmann/montepython_public#21]
Hi I'm learning how to use the montepython code through some tests.
I'm really in the beginning step.
I ran the code with
`~/research/software/monte_python/montepython_public$ python montepython/MontePython.py run -o sdss_lrg/ -p input/sdss_lrgDR7.param`

and the tried to analyze and plot the result with
`~/research/software/monte_python/montepython_public$ python montepython/MontePython.py info sdss_lrg/ --extra plot_files/example.plot`

then at first I get this error message
```
Running Monte Python v3.0.1

Traceback (most recent call last):
  File "montepython/MontePython.py", line 42, in <module>
    sys.exit(run())
  File "/home/sjc2/research/software/monte_python/montepython_public/montepython/run.py", line 31, in run
    custom_command)
  File "/home/sjc2/research/software/monte_python/montepython_public/montepython/run.py", line 188, in safe_initialisation
    cosmo, data, command_line, success = initialise(custom_command)
  File "/home/sjc2/research/software/monte_python/montepython_public/montepython/initialise.py", line 58, in initialise
    analyze(command_line)
  File "/home/sjc2/research/software/monte_python/montepython_public/montepython/analyze.py", line 76, in analyze
    info = Information(command_line)
  File "/home/sjc2/research/software/monte_python/montepython_public/montepython/analyze.py", line 2091, in __init__
    execfile(command_line.optional_plot_file, plot_file_vars)
  File "plot_files/example.plot", line 46
    info.force_limits = ('H0':[60:70],'z_reio':[5:15])
                             ^
SyntaxError: invalid syntax
```

so I changed the line of example.plot 'info.force_limits = ('H0':[60:70],'z_reio':[5:15])' 
to ('H0'==[60,70],'z_reio'==[5,15])'.

Then the new error is came up....
```
Running Monte Python v3.0.1

--> Scanning file test/2018-11-14_10000__1.txt : Removed 0 non-markovian points, 15 points of burn-in, keep 91 steps
 /!\ Convergence computed for a single file
 /|\  Transforming omega_cdm into (0.01*omega_b+omega_cdm)/(H0/100.)**2
/_o_\ The new variable will be called $\Omega_\mathrm{m}$
Traceback (most recent call last):
  File "montepython/MontePython.py", line 42, in <module>
    sys.exit(run())
  File "/home/sjc2/research/software/monte_python/montepython_public/montepython/run.py", line 31, in run
    custom_command)
  File "/home/sjc2/research/software/monte_python/montepython_public/montepython/run.py", line 188, in safe_initialisation
    cosmo, data, command_line, success = initialise(custom_command)
  File "/home/sjc2/research/software/monte_python/montepython_public/montepython/initialise.py", line 58, in initialise
    analyze(command_line)
  File "/home/sjc2/research/software/monte_python/montepython_public/montepython/analyze.py", line 92, in analyze
    convergence(info)
  File "/home/sjc2/research/software/monte_python/montepython_public/montepython/analyze.py", line 270, in convergence
    info.remap_parameters(spam)
  File "/home/sjc2/research/software/monte_python/montepython_public/montepython/analyze.py", line 2129, in remap_parameters
    exec("spam[i][:, %i] = %s" % (index_to_change, value))
  File "<string>", line 1, in <module>
NameError: name 'H0' is not defined
```
How can I solve this problem?

**Comment by brinckmann** [comment]
Hi,
Thanks for reminding me to fix the example plot file! It should normally be
`info.force_limits = {'H0':[60,70],'z_reio':[5,15]}`
But in your case you don't have H0 as a parameter. Since you instead have h, you would want
`info.force_limits = {'h':[0.60,0.70],'z_reio':[5,15]}`
Or you can comment the line entirely.

Best,
Thejs

**Comment by mubecks** [comment]
Hi,
Thanks for the solution and it works for the plotting I think.
But do I need latex for saving the plot or result from example.plot?
Cause the message says,
```
--> Saving figures to .pdf files
Traceback (most recent call last):
  File "montepython/MontePython.py", line 42, in <module>
    sys.exit(run())
.
.
.
OSError: [Errno 2] No such file or directory: 'latex'
```
Thanks,
YB
