### ISSUE TITLE
ValueError occurs when MontePython.py info

### ISSUE THREAD

**Issue by PhyPy-Dm** [brinckmann/montepython_public#211]
Hi everyone!
   When the chains running finished, and I type `MontePython.py info` to get my analysis, a ValueError occurs, the details are as followings：

`(base) hejiayin@magic:~/MCMClass/montepython$ python montepython/MontePython.py info outputplc2018
Running Monte Python v3.4.0

--> Scanning file outputplc2018/2021-05-26_5000__1.txt: Removed 0 non-markovian points, 0 points of burn-in, keep 1003 steps
 /!\ Convergence computed for a single file
--> Computing mean values
--> Computing variance
--> Computing convergence criterium (Gelman-Rubin)
 -> R-1 is 0.000518 	for  omega_b
           0.001742 	for  omega_cdm
           0.000308 	for  100*theta_s
           0.003779 	for  ln10^{10}A_s
           0.000635 	for  n_s
           0.002712 	for  tau_reio
           0.002985 	for  A_cib_217
           0.007823 	for  xi_sz_cib
           0.001285 	for  A_sz
           0.003986 	for  ps_A_100_100
           0.006723 	for  ps_A_143_143
           0.003226 	for  ps_A_143_217
           0.004334 	for  ps_A_217_217
           0.000540 	for  ksz_norm
           0.002676 	for  gal545_A_100
           0.000096 	for  gal545_A_143
           0.000153 	for  gal545_A_143_217
           0.000143 	for  gal545_A_217
           0.000132 	for  galf_TE_A_100
           0.001690 	for  galf_TE_A_100_143
           0.000928 	for  galf_TE_A_100_217
           0.007692 	for  galf_TE_A_143
           0.001610 	for  galf_TE_A_143_217
           0.001567 	for  galf_TE_A_217
           0.001910 	for  calib_100T
           0.000180 	for  calib_217T
           0.000210 	for  A_planck
           0.002914 	for  z_reio
           0.002608 	for  Omega_Lambda
           0.002429 	for  YHe
           0.001511 	for  H0
           0.003640 	for  A_s
           0.005977 	for  sigma8
-----------------------------------------------
 -> Computing histograms for  omega_b
 /!\ could not derive minimum credible intervals for this multimodal posterior
 /!\ please try running longer chains or reducing the number of bins with --bins
     BINS (default: 20)
 -> Computing histograms for  omega_cdm
 /!\ could not derive minimum credible intervals for this multimodal posterior
 /!\ please try running longer chains or reducing the number of bins with --bins
     BINS (default: 20)
Traceback (most recent call last):
  File "montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/home/hejiayin/MCMClass/montepython/montepython/run.py", line 31, in run
    cosmo, data, command_line, success = safe_initialisation(
  File "/home/hejiayin/MCMClass/montepython/montepython/run.py", line 191, in safe_initialisation
    cosmo, data, command_line, success = initialise(custom_command)
  File "/home/hejiayin/MCMClass/montepython/montepython/initialise.py", line 59, in initialise
    analyze(command_line)
  File "/home/hejiayin/MCMClass/montepython/montepython/analyze.py", line 167, in analyze
    compute_posterior(information_instances)
  File "/home/hejiayin/MCMClass/montepython/montepython/analyze.py", line 1017, in compute_posterior
    ax2dsub.set_xticklabels([''])
  File "/home/hejiayin/.local/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 63, in wrapper
    return get_method(self)(*args, **kwargs)
  File "/home/hejiayin/.local/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py", line 451, in wrapper
    return func(*args, **kwargs)
  File "/home/hejiayin/.local/lib/python3.8/site-packages/matplotlib/axis.py", line 1796, in _set_ticklabels
    return self.set_ticklabels(labels, minor=minor, **kwargs)
  File "/home/hejiayin/.local/lib/python3.8/site-packages/matplotlib/axis.py", line 1717, in set_ticklabels
    raise ValueError(
ValueError: The number of FixedLocator locations (3), usually from a call to set_ticks, does not match the number of ticklabels (1).
`

and there're  5000 steps done, acceptance rate is 0.2004, I don't know if 5000 is so small or the acceptance is bad. Does anybody know what to do about it？

**Comment by brinckmann** [comment]
You can check these two issues and see if the solutions proposed there work for you: #154 #185 

Best,
Thejs

**Comment by PhyPy-Dm** [comment]
@brinckmann Dear Thejs, I chage the lines : `ax2dsub.set_xticklabels(['']) ->ax2dsub.set_xticklabels([])
   ax2dsub.set_yticklabels(['']) -> ax2dsub.set_yticklabels([])`, which is mentioned in issue #154, and I get new errors as following

`**--> Saving figures to .pdf files
Traceback (most recent call last):
  File "/home/hejiayin/.local/lib/python3.8/site-packages/matplotlib/texmanager.py", line 275, in _run_checked_subprocess
    report = subprocess.check_output(command,
  File "/home/hejiayin/anaconda3/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/hejiayin/anaconda3/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/hejiayin/anaconda3/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/hejiayin/anaconda3/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'latex'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/home/hejiayin/MCMClass/montepython/montepython/run.py", line 31, in run
    cosmo, data, command_line, success = safe_initialisation(custom_command)
  File "/home/hejiayin/MCMClass/montepython/montepython/run.py", line 190, in safe_initialisation
    cosmo, data, command_line, success = initialise(custom_command)
  File "/home/hejiayin/MCMClass/montepython/montepython/initialise.py", line 59, in initialise
    analyze(command_line)
  File "/home/hejiayin/MCMClass/montepython/montepython/analyze.py", line 167, in analyze
    compute_posterior(information_instances)
  File "/home/hejiayin/MCMClass/montepython/montepython/analyze.py", line 1098, in compute_posterior
    fig2d.savefig(
  File "/home/hejiayin/.local/lib/python3.8/site-packages/matplotlib/figure.py", line 2311, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/hejiayin/.local/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2193, in print_figure
    self.figure.draw(renderer)
  File "/home/hejiayin/.local/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/hejiayin/.local/lib/python3.8/site-packages/matplotlib/figure.py", line 1863, in draw
    mimage._draw_list_compositing_images(
  File "/home/hejiayin/.local/lib/python3.8/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/hejiayin/.local/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/hejiayin/.local/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py", line 411, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/home/hejiayin/.local/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 2747, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/home/hejiayin/.local/lib/python3.8/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/hejiayin/.local/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/hejiayin/.local/lib/python3.8/site-packages/matplotlib/axis.py", line 1165, in draw
    ticklabelBoxes, ticklabelBoxes2 = self._get_tick_bboxes(ticks_to_draw,
  File "/home/hejiayin/.local/lib/python3.8/site-packages/matplotlib/axis.py", line 1091, in _get_tick_bboxes
    return ([tick.label1.get_window_extent(renderer)
  File "/home/hejiayin/.local/lib/python3.8/site-packages/matplotlib/axis.py", line 1091, in <listcomp>
    return ([tick.label1.get_window_extent(renderer)
  File "/home/hejiayin/.local/lib/python3.8/site-packages/matplotlib/text.py", line 902, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "/home/hejiayin/.local/lib/python3.8/site-packages/matplotlib/text.py", line 287, in _get_layout
    _, lp_h, lp_d = renderer.get_text_width_height_descent(
  File "/home/hejiayin/.local/lib/python3.8/site-packages/matplotlib/backends/_backend_pdf_ps.py", line 86, in get_text_width_height_descent
    w, h, d = texmanager.get_text_width_height_descent(
  File "/home/hejiayin/.local/lib/python3.8/site-packages/matplotlib/texmanager.py", line 423, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)
  File "/home/hejiayin/.local/lib/python3.8/site-packages/matplotlib/texmanager.py", line 309, in make_dvi
    self._run_checked_subprocess(
  File "/home/hejiayin/.local/lib/python3.8/site-packages/matplotlib/texmanager.py", line 279, in _run_checked_subprocess
    raise RuntimeError(
RuntimeError: Failed to process string with tex because latex could not be found**`

but I install latex by `pip install latex`, which did't fix it

**Comment by PhyPy-Dm** [comment]
@brinkmann Dear Thejs, and the same problem still exists: 

` -> Computing histograms for  omega_cdm
 /!\ could not derive minimum credible intervals for this multimodal posterior
 /!\ please try running longer chains or reducing the number of bins with --bins
     BINS (default: 20)`

but I have get chiains for 40000 steps,  and I try `--bins 10`, it does't work, how can I solve it?

**Comment by brinckmann** [comment]
Maybe your chains aren't well enough converged? It says the posterior is multimodal, which might indicate it's not properly converged unless you're expecting a multimodal distribution.

Best,
Thejs

**Comment by PhyPy-Dm** [comment]
@brinckmann Dear Thejs, how to solve the latex problem? I have install latex by `pip`.

**Comment by shan1525** [comment]
Hi @PhyPy-Dm , 

For the latex problem I can suggest you this link. Try the suggestion that is given in here, 
https://stackoverflow.com/questions/54477891/filenotfounderror-errno-2-no-such-file-or-directory-latex-latex-python. 
Try if this helps, specifically the 10th no. suggestion. 

Best, 
Shan.

**Comment by PhyPy-Dm** [comment]
Dear @shan1525 ,
Thank you so much, now I have fixed the latex problem.

Best
PhyPy-Dm

**Comment by PhyPy-Dm** [comment]
Dear @brinckmann 
I follow your suggestion #154 #185 to solve  ticks problem, and it works, thank you very much.  And could your give me some advice on making the chains converged? I have no idea about it.

Best
PhyPy-Dm
