### ISSUE TITLE
TypeError while adding more derived parameters

### ISSUE THREAD

**Issue by Uendert** [brinckmann/montepython_public#213]
Hi all,

I ran into an error while adding more derived parameters with Der method.

Here is an example to what I did:
`python montepython/MontePython.py run -p input/pantheon.param -o chains/pantheon/ -m Der --Der-target-folder 
chains/pantheon_Der --Der-param-list Omega_m`

And I got the following error: `TypeError: cannot serialize '_io.TextIOWrapper' object`. 
Please, see below for the full error message.

> Start extracting the chains:
Traceback (most recent call last):
  File "montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/home/uendertandrade/montepython_public/montepython/run.py", line 45, in run
    sampler.run(cosmo, data, command_line)
  File "/home/uendertandrade/montepython_public/montepython/sampler.py", line 62, in run
    der.run(cosmo, data, command_line)
  File "/home/uendertandrade/montepython_public/montepython/add_derived.py", line 76, in run
    pool.map(extend_chain_star, args)
  File "/home/uendertandrade/anaconda3/envs/kcap_env/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/uendertandrade/anaconda3/envs/kcap_env/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/home/uendertandrade/anaconda3/envs/kcap_env/lib/python3.7/multiprocessing/pool.py", line 431, in _handle_tasks
    put(task)
  File "/home/uendertandrade/anaconda3/envs/kcap_env/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/uendertandrade/anaconda3/envs/kcap_env/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot serialize '_io.TextIOWrapper' object

------------------------------

- Version:
-- Monte Python v3.4.0
-- CLASS v2.9.4

Cheers,
Uendert

**Comment by dchooper** [comment]
Hi,

I'm closing this as stale given how long ago it was opened - feel free to reopen it if problem persists!

This looks to me like the parameter Omega_m was being defined twice - I'm wondering if giving it another name would have solved the problem. 

Cheers,
Deanna
