### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by am610** [brinckmann/montepython_public#227]
Error while trying to plot

`python montepython/MontePython.py info output/SNANA_plasticc_p/ `

I get this error 

`Traceback (most recent call last):
  File "montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/global/cscratch1/sd/ayanmitr/montepython_V3/montepython/run.py", line 32, in run
    custom_command)
  File "/global/cscratch1/sd/ayanmitr/montepython_V3/montepython/run.py", line 191, in safe_initialisation
    cosmo, data, command_line, success = initialise(custom_command)
  File "/global/cscratch1/sd/ayanmitr/montepython_V3/montepython/initialise.py", line 59, in initialise
    analyze(command_line)
  File "/global/cscratch1/sd/ayanmitr/montepython_V3/montepython/analyze.py", line 151, in analyze
    enumerate(info.chain[info.sorted_indices[0], 2:])]:
IndexError: index 3 is out of bounds for axis 0 with size 3`

What is the error, I am wondering?

**Comment by dchooper** [comment]
Probable cause/solution reported in issue #257 .
