### ISSUE TITLE
analyzing issue

### ISSUE THREAD

**Issue by mubecks** [brinckmann/montepython_public#24]
Hi again,

I'm trying to analyze the test output running with example.param and fake_planck likelihood.
But when I run the command I got the error about not enough chains.
```
montepython_public> montepython/MontePython.py info test_planck/fake_planck/
Running Monte Python v3.0.1

--> Scanning file test_planck/fake_planck/2018-11-20_5__2.txt : Removed 0 non-markovian points, 4 points of burn-in, keep 1 steps
                                          2018-11-20_5__3.txt : Removed everything: chain not converged
                                          2018-11-20_5__1.txt : Removed everything: chain not converged
Traceback (most recent call last):
  File "montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/global/u2/l/leeyounb/cori/software/code/montepython_public/montepython/run.py", line 31, in run
    custom_command)
  File "/global/u2/l/leeyounb/cori/software/code/montepython_public/montepython/run.py", line 188, in safe_initialisation
    cosmo, data, command_line, success = initialise(custom_command)
  File "/global/u2/l/leeyounb/cori/software/code/montepython_public/montepython/initialise.py", line 58, in initialise
    analyze(command_line)
  File "/global/u2/l/leeyounb/cori/software/code/montepython_public/montepython/analyze.py", line 92, in analyze
    convergence(info)
  File "/global/u2/l/leeyounb/cori/software/code/montepython_public/montepython/analyze.py", line 268, in convergence
    spam = remove_bad_points(info)
  File "/global/u2/l/leeyounb/cori/software/code/montepython_public/montepython/analyze.py", line 1849, in remove_bad_points
    "Please wait a bit to analyze this folder")
io_mp.AnalyzeError: 

Analyze Error:
 /|\   No decently sized chain was found. Please wait a bit to analyze this
/_o_\  folder
```

**Comment by brinckmann** [comment]
Hi,

Probably my answer is not helpful anymore since so much time has gone by, but your chains do not appear to be converged as you need to let them run for more time. It looks like you ran them with 5 data points, which is much too little, try e.g. 10000 passed with the flag -N 10000 .

Best,
Thejs
