### ISSUE TITLE
configuration error when running MontePython.py run -o test -p example.param

### ISSUE THREAD

**Issue by Rockdeldiablo** [brinckmann/montepython_public#246]
hi to everyone, 
i am a new user (both for monte python and linux in general) so i probably messed up something during the installation procedure.  I tried to follow the instruction but evidently i messed up somewhere.
 when i run :
`python3 montepython/MontePython.py run -o test -p example.param`

i get:

```
`
Configuration Error:
 /|\   argument -p/--param: The file 'example.param' does not exist

Traceback (most recent call last):
  File "/home/pasquale/anaconda3/lib/python3.8/argparse.py", line 2422, in _get_value
    result = type_func(arg_string)
  File "/home/pasquale/Documents/lesgourg/mp/montepython_public/montepython/parser_mp.py", line 120, in existing_file
    raise ap.ArgumentTypeError(msg)
argparse.ArgumentTypeError: The file 'example.param' does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pasquale/anaconda3/lib/python3.8/argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/pasquale/anaconda3/lib/python3.8/argparse.py", line 2006, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/home/pasquale/anaconda3/lib/python3.8/argparse.py", line 1946, in consume_optional
    take_action(action, args, option_string)
  File "/home/pasquale/anaconda3/lib/python3.8/argparse.py", line 1858, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/home/pasquale/anaconda3/lib/python3.8/argparse.py", line 2389, in _get_values
    value = self._get_value(action, arg_string)
  File "/home/pasquale/anaconda3/lib/python3.8/argparse.py", line 2428, in _get_value
    raise ArgumentError(action, msg)
argparse.ArgumentError: argument -p/--param: The file 'example.param' does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pasquale/Documents/lesgourg/mp/montepython_public/montepython/run.py", line 191, in safe_initialisation
    cosmo, data, command_line, success = initialise(custom_command)
  File "/home/pasquale/Documents/lesgourg/mp/montepython_public/montepython/initialise.py", line 31, in initialise
    command_line = parser_mp.parse(custom_command)
  File "/home/pasquale/Documents/lesgourg/mp/montepython_public/montepython/parser_mp.py", line 1053, in parse
    args = parser.safe_parse_args()
  File "/home/pasquale/Documents/lesgourg/mp/montepython_public/montepython/parser_mp.py", line 47, in safe_parse_args
    return self.parse_args(args)
  File "/home/pasquale/anaconda3/lib/python3.8/argparse.py", line 1768, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/home/pasquale/anaconda3/lib/python3.8/argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/pasquale/anaconda3/lib/python3.8/argparse.py", line 1988, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/home/pasquale/anaconda3/lib/python3.8/argparse.py", line 1965, in consume_positionals
    take_action(action, args)
  File "/home/pasquale/anaconda3/lib/python3.8/argparse.py", line 1874, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/pasquale/anaconda3/lib/python3.8/argparse.py", line 1159, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/home/pasquale/anaconda3/lib/python3.8/argparse.py", line 1807, in parse_known_args
    self.error(str(err))
  File "/home/pasquale/Documents/lesgourg/mp/montepython_public/montepython/parser_mp.py", line 37, in error
    raise io_mp.ConfigurationError(message)
io_mp.ConfigurationError: 

Configuration Error:
 /|\   argument -p/--param: The file 'example.param' does not exist


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/home/pasquale/Documents/lesgourg/mp/montepython_public/montepython/run.py", line 31, in run
    cosmo, data, command_line, success = safe_initialisation(
  File "/home/pasquale/Documents/lesgourg/mp/montepython_public/montepython/run.py", line 197, in safe_initialisation
    raise io_mp.ConfigurationError(
io_mp.ConfigurationError: 

Configuration Error:
 /|\   The initialisation was not successful, resulting in a potentially half
/_o_\  created `log.param`. Please see the above error message. If you run the
       exact same command, it will not work. You should solve the problem, and
       try again.
`

```

and i have no idea how to fix this.

the  --help commands work tho

`python3 montepython/MontePython.py run --help`
and
`python3 montepython/MontePython.py info --help`

any advice? thanks

**Comment by brinckmann** [comment]
As the error message says the file cannot be found. This is because the example param file you're looking for is in the `input/` directory, i.e. `input/example.param`

When trying again make sure to start in a clean chains directory by changing the output name or deleting the test directory (if one was created).

Best,
Thejs

**Comment by Rockdeldiablo** [comment]
> As the error message says the file cannot be found. This is because the example param file you're looking for is in the `input/` directory, i.e. `input/example.param`
> 
> When trying again make sure to start in a clean chains directory by changing the output name or deleting the test directory (if one was created).
> 
> Best, Thejs

i feel so stupid right now, after 2 days spent setting up ubuntu, fixing GRUB, and solving the various installation issues i didn't even think about the folder.
thanks, looks like  this step works now.
