### ISSUE TITLE
KeyError: 'current'

### ISSUE THREAD

**Issue by shan1525** [brinckmann/montepython_public#249]
Hi everyone,
I am running montepython 3.4 with class version 3.0.1 in the cluster. I have compiled everything with python 3.6.  I checked the pymultinest sepetately it is running when I run python pymultinest_demo.py. I have also set the global path for pymultinest as well. I have also checked the class with python wrapper. When I am importing classy , it is not giving me any error. Then I also checked the planck code as well. it is also running seperately. But when I try to run the montepython , it is giving me some errors in data.py module. The detailes of my error is the following:

when I run the Pantheon likelihood with planck , bao ans shoes , It is giving an error in read matrix like this ;
Running Monte Python v3.4.0

with CLASS v3.0.1

Testing likelihoods for:
 ->Planck_highl_TTTEEE, Planck_lowl_EE, Planck_lowl_TT, Planck_lensing, bao_boss_dr12, bao_smallz_2014, Pantheon, sh0es

----
clik version plc_3.1
  smica
Checking likelihood '/mnt/home/associate/csomasri/shaz/cluster_monte/code/plc_3.0/plc-3.1/../../../baseline/plc_3.0/hi_l/plik/plik_rd12_HM_v22b_TTTEEE.clik' on test data. got -1172.47 expected -1172.47 (diff -4.34053e-07)
----
-----
Traceback (most recent call last):
  File "/mnt/home/associate/csomasri/shaz/cluster_monte/montepython_public-3.4/montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/mnt/home/associate/csomasri/shaz/cluster_monte/montepython_public-3.4/montepython/run.py", line 32, in run
    custom_command)
  File "/mnt/home/associate/csomasri/shaz/cluster_monte/montepython_public-3.4/montepython/run.py", line 191, in safe_initialisation
    cosmo, data, command_line, success = initialise(custom_command)
  File "/mnt/home/associate/csomasri/shaz/cluster_monte/montepython_public-3.4/montepython/initialise.py", line 67, in initialise
    data = Data(command_line, path)
  File "/mnt/home/associate/csomasri/shaz/cluster_monte/montepython_public-3.4/montepython/data.py", line 356, in __init__
    self.initialise_likelihoods(self.experiments)
  File "/mnt/home/associate/csomasri/shaz/cluster_monte/montepython_public-3.4/montepython/data.py", line 493, in initialise_likelihoods
    elem, elem, folder, elem))
  File "<string>", line 1, in <module>
  File "/mnt/home/associate/csomasri/shaz/cluster_monte/montepython_public-3.4/montepython/likelihoods/Pantheon/__init__.py", line 54, in __init__
    self.C00 = self.read_matrix(self.mag_covmat_file)
  File "/mnt/home/associate/csomasri/shaz/cluster_monte/montepython_public-3.4/montepython/likelihood_class.py", line 2499, in read_matrix
    matrix = read_table(path).to_numpy().reshape((length, length))
  File "/mnt/csoft/tools/anaconda3-5-2-0/lib/python3.6/site-packages/pandas/core/generic.py", line 4372, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'to_numpy'.  

So, I changed 
matrix = read_table(path).to_numpy().reshape((length, length)) to 
matrix = read_table(path).values.reshape((length, length)). as suggested in #98.

After that when I ran the program , it is giving me a key error which is as follows:
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/mnt/home/associate/csomasri/.local/lib/python3.6/site-packages/pymultinest-2.11-py3.6.egg/pymultinest/run.py", line 225, in loglike
   Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/mnt/home/associate/csomasri/.local/lib/python3.6/site-packages/pymultinest-2.11-py3.6.egg/pymultinest/run.py", line 225, in loglike
    folder = original[index+1]
  File "/mnt/home/associate/csomasri/shaz/cluster_monte/montepython_public-3.4/montepython/MultiNest.py", line 271, in loglike
    data.update_cosmo_arguments()
  File "/mnt/home/associate/csomasri/shaz/cluster_monte/montepython_public-3.4/montepython/data.py", line 805, in update_cosmo_arguments
    self.mcmc_parameters[elem]['current'] *\
KeyError: 'current'

I also checked it without the pantheon data. But the key error still persists. I checked all the related issuees in the issue page. But I couldn't find one to resolve this. I have exhausted everything little thing that I could know of.

If Anyone has an idea to resolve this, Please do reply. I will be grateful.

with the best regards,
shan.

**Comment by shan1525** [comment]
Update: 
I have been able to figure out where the problem is . It is  when I use the pantheon and plannck lensing likelihoods.I checked all the import modules. It is working. I checked as follows:
![import_modules](https://user-images.githubusercontent.com/70058996/143405044-892bcf5e-a5ff-45db-aedd-432650a2d9f2.png)
 
I checked that the example.param is running. I also checked with base2018TTTEEE.param is running. But when I try to run it with pantheon and planck lensing it is not working. The pantheon one is giving error in read.matrix part and  The lensing one is giving the key error. I also checked with -m NS , it behaves the same as it is working without the pantheon and planck lensing likelilihood. The problem is I don't know to resolve the problem. Please, guide me through this. If anyone has any idea, please feel free to suggest. 

with the best regards,
shan.

**Comment by shan1525** [comment]
Update:

Hi everyone,

Regarding the issues, I had two of them. So, I was able to solve the readmatrix problem by upgrading the pandas. I had pandas version 0.23 which is compatible with python 2.7. But python 3 needs version >0.24. So, upgrading pandas solved that problem. About , The key error with the method -NS , There is already an issue opened in Baudren page. So I considered that. If anyone is facing similar kind of issue as mine please look https://github.com/baudren/montepython_public/issues/53. 

I am closing this issue now as it has been resolved.
with the best regards,
shan.
P.S. I should have made a brief description in my first comment so that anyone could see it properly.
