### ISSUE TITLE
Problem whit running timedelay_6lenses likelihood

### ISSUE THREAD

**Issue by HugoGarcia22** [brinckmann/montepython_public#260]
When I run the montepython likelihood for holicow (timedelay_6lenses), I got this problem

Running Monte Python v3.4.0

with CLASS v3.0.0

Testing likelihoods for:
 ->timedelay_6lenses

Traceback (most recent call last):
  File "montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/home/hugo/montepython/montepython/run.py", line 32, in run
    custom_command)
  File "/home/hugo/montepython/montepython/run.py", line 191, in safe_initialisation
    cosmo, data, command_line, success = initialise(custom_command)
  File "/home/hugo/montepython/montepython/initialise.py", line 67, in initialise
    data = Data(command_line, path)
  File "/home/hugo/montepython/montepython/data.py", line 356, in __init__
    self.initialise_likelihoods(self.experiments)
  File "/home/hugo/montepython/montepython/data.py", line 493, in initialise_likelihoods
    elem, elem, folder, elem))
  File "<string>", line 1, in <module>
  File "/home/hugo/montepython/montepython/likelihoods/timedelay_6lenses/__init__.py", line 62, in __init__
    self.wfi2033_dt_fit_kde = gaussian_kde(wfi2033dist[0], weights = wfi2033dist[1])
TypeError: __init__() got an unexpected keyword argument 'weights'

**Comment by HugoGarcia22** [comment]
I just solved upgrading the spicy version ti 1.2.1
