### ISSUE TITLE
Conditions on parameters while sampling

### ISSUE THREAD

**Issue by tanmoyyy** [brinckmann/montepython_public#266]
Dear All,

Is there a way I can set conditions on 'cosmo' parameters while sampling? E.g., I have three cosmo parameters as
data.parameters['a1'] = [ 1.5, -1, 10, 0.01, 1, 'cosmo']  
data.parameters['a2'] = [ 0.9, -1, 20, 0.01, 1, 'cosmo'] 
data.parameters['a3'] = [ 0.01, -10, 20, 0.1, 1, 'cosmo']   

What I want is to set a condition (a3 < a1 * a2) while sampling. Is there any easy way to do this with NS or MH in MontePython?
This is perhaps very trivial but would very much appreciate if anyone can guide me to a discussion on this.

Thanks,
Tanmoy

**Comment by tanmoyyy** [comment]
Dear Thejs,

Many thanks for the quick reply and the links. Unfortunately once the condition is violated CLASS stops working and MontePython stops as well with error message on the violation on the condition. Actually  I was trying to reproduce the constraints on general isocurvature modes from Planck 2015  paper with "data.cosmo_arguments['P_k_ini type'] = 'two_scales' ".  At some point the required  conditions between the adiabatic, isocurvature and cross correlation get violated. Was hoping CLASS would ignore but it did not.

Regards,
Tanmoy

**Comment by tanmoyyy** [comment]
Dear Thejs,

Thank you for the suggestion. I implemented the above replacement (with modified conditions as per my needs)

------------------------------------------------------------------------
#               cosmo.compute()
             try:
                if (data.mcmc_parameters['P_{RI}^1']['current'])**2/(data.mcmc_parameters['P_{RR}^1']['current']*data.mcmc_parameters['P_{II}^1']['current']) < 1.0:
                  cosmo_compute = True
                else:
                   cosmo_compute = False
             except:
                  cosmo_compute = True
             if cosmo_compute:
                 cosmo.compute()
             else:
                 return data.boundary_loglike
-----------------------------------------------



But my test run
"../montepython_public/montepython/MontePython.py run -p ../montepython_public/testrun/input/test.param  -o ../montepython_public/testrun/chains/ -N 10" returned the following error

----------------------------------------------------
Traceback (most recent call last):
  File "../montepython_public/montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "../montepython_public/montepython/run.py", line 32, in run
    custom_command)
  File "../montepython_public/montepython/run.py", line 191, in safe_initialisation
    cosmo, data, command_line, success = initialise(custom_command)
  File "../montepython_public/montepython/initialise.py", line 67, in initialise
    data = Data(command_line, path)
  File "../montepython_public/montepython/data.py", line 213, in __init__
    self.fill_mcmc_parameters()
  File "../montepython_public/montepython/data.py", line 400, in fill_mcmc_parameters
    self.read_file(self.param, 'data')
  File "../montepython_public/montepython/data.py", line 580, in read_file
    exec(statement.rstrip())
  File "<string>", line 1, in <module>
NameError: name 'none' is not defined
-------------------------------------------------------

Any suggestion?

Regards,
Tanmoy

**Comment by tanmoyyy** [comment]
Dear Thejs,

It seems to be working now (ignore my previous msgs if you received any). Will let you know if I get any error. Thanks as always for your kind help.


BTW, Are "lmax" in line 1454 and 1463  in "likelihood_class.py" should be "l_max"?  And should "cl[l]['bb']=cl_unlensed[l]['bb']" in lines 1455 and 1464 be "cl['bb'][l]=cl_unlensed['bb'][l]"? Am I missing something? I am using version 3.5.0.

Regards,
Tanmoy

**Comment by tanmoyyy** [comment]
Dear Thejs,

Sorry to bother you once more.Your solution worked without any error! 

How could I use this condition with Nested sampling? From the previous reply I gather the solution was only for  Metropolis-Hastings? What change should I have to make for Nested Sampling? 

Regards,
Tanmoy
