### ISSUE TITLE
Error message when running lowl_EE + lowl_TT + highl_TTTEEE_lite likelihoods 

### ISSUE THREAD

**Issue by matt11111111111** [brinckmann/montepython_public#285]
Hi, 

I would like to run the 

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "/share/splinter/mgrasso/kcap_env_hiclass/lib/python3.7/site-packages/pymultinest/run.py", line 221, in loglike
    return LogLikelihood(cube, ndim, nparams)
  File "/share/splinter/mgrasso/montepython_public/montepython/MultiNest.py", line 272, in loglike
    lkl = sampler.compute_lkl(cosmo, data)
  File "/share/splinter/mgrasso/montepython_public/montepython/sampler.py", line 776, in compute_lkl
    value = likelihood.loglkl(cosmo, data)
  File "/share/splinter/mgrasso/montepython_public/montepython/likelihood_class.py", line 1051, in loglkl
    lkl = self.clik(tot)[0]
  File "lkl.pyx", line 89, in clik.lkl.clik.__call__
clik.lkl.CError: <exception str() failed>

**Comment by dchooper** [comment]
Hi,

The first thing to check is if clik was installed correctly. Try opening up a python instance in your terminal and see if `import clik` works. If that works, we can move on to the next test.

As a side note, it is better if your Planck likelihoods always have the highl part first, as there is a nuisance parameter there that is taken for the other likelihoods. This can sometimes lead to problems, so make sure your ordering is "highl_TTTEEE_lite, lowl_TT, lowl_EE".

Cheers,
Deanna
