### ISSUE TITLE
How to apply other parameter file?

### ISSUE THREAD

**Issue by dlalstjq** [brinckmann/montepython_public#358]
Hello! I'm a student studying cosmology
I installed montepython following README file and it worked when input file is input/example.param.
But I get error like under when input is another parameter file. 
I don't know how to solve this problem, How can I solve this error?

(base) minsub@Lee:/home/minsub/data/montepython_public-3.6$ python montepython/MontePython.py run -p input/base2015TTTEEE.param -o chains/base2015TTTEEE -N 100000
 /!\ PyMultiNest detected but MultiNest likely not installed correctly. You can
     safely ignore this if not running with option -m NS
 /!\ Appending to an existing folder: using the log.param instead of
     input/base2015TTTEEE.param
Running Monte Python v3.6.0

Traceback (most recent call last):
  File "/home/minsub/data/montepython_public-3.6/montepython/run.py", line 191, in safe_initialisation
    cosmo, data, command_line, success = initialise(custom_command)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/minsub/data/montepython_public-3.6/montepython/initialise.py", line 67, in initialise
    data = Data(command_line, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/minsub/data/montepython_public-3.6/montepython/data.py", line 214, in __init__
    self.fill_mcmc_parameters()
  File "/home/minsub/data/montepython_public-3.6/montepython/data.py", line 401, in fill_mcmc_parameters
    self.read_file(self.param, 'data')
  File "/home/minsub/data/montepython_public-3.6/montepython/data.py", line 581, in read_file
    exec(statement.rstrip())
  File "<string>", line 1, in <module>
KeyError: 'cosmo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/minsub/data/montepython_public-3.6/montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/minsub/data/montepython_public-3.6/montepython/run.py", line 31, in run
    cosmo, data, command_line, success = safe_initialisation(
                                         ^^^^^^^^^^^^^^^^^^^^
  File "/home/minsub/data/montepython_public-3.6/montepython/run.py", line 206, in safe_initialisation
    raise io_mp.ConfigurationError(
io_mp.ConfigurationError: 

Configuration Error:
 /|\   You are running in a folder that was created following a non-successful
/_o_\  initialisation (wrong parameter name, wrong likelihood, etc...). If you
       have solved the issue, you should remove completely the output folder,
       and try again. Alternatively, there could be a problem with 'cosmo'

double free or corruption (!prev)
Aborted (core dumped)

**Comment by brinckmann** [comment]
Hi,

For each new run (e.g. with a new parameter file) you need to create a new chains directory, you cannot run in an existing one.

This is all explained in the MontePython guides on the [course page of Julien Lesgourgues](https://lesgourg.github.io/courses.html) and a [recorded lecture from the CosmoTools18 school](https://indico.cern.ch/event/688110/timetable/?print=1&view=standard) . You might also find useful information in the [official MontePython paper ](https://arxiv.org/abs/1804.07261) . I hope this helps.

Best,
Thejs

**Comment by dlalstjq** [comment]
Thanks to advice.

I run the code with new directory, and I find the reason of error. I think something wrong in install planck likelihood part.

**Comment by brinckmann** [comment]
Hi,

It looks like it's having problems with your Python installation. This can be tricky, you'll want to make sure it knows about the relevant python directories, that they're specified in the relevant system paths, and is trying to run the right python installation, although sometimes I've been able to install Planck with the python wrapper even when it throws some Python errors, it can be a bit finnicky. Also, you see it has a problem with your lapack installation and gives you a suggestion for what to do.

Since this is not a MontePython issue our help will be limited. Here are ways to get further information on installing Planck:

- The MontePython README: https://github.com/brinckmann/montepython_public#the-planck-likelihood-part
- The Planck README found in your Planck directory at code/plc_3.0/plc-3.01/readme.md
- Searching for Planck in open and closed MontePython issues as common problems have been addressed many times: https://github.com/brinckmann/montepython_public/issues?q=is%3Aissue+Planck
- Searching for answered Planck issues on the CosmoCoffee forums https://cosmocoffee.info/

Best,
Thejs
