### ISSUE TITLE
An error while running Montepython

### ISSUE THREAD

**Issue by SuvedhaNaik** [brinckmann/montepython_public#68]
Hi All,
I recently encountered an error while running montepython. After this error, the program stopped running. I couldn't figure out the cause. Did anyone encounter the same? 

`Traceback (most recent call last):
  File "montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/SUVEDHA/montepython_public-master/montepython/run.py", line 44, in run
    sampler.run(cosmo, data, command_line)
  File "/SUVEDHA/montepython_public-master/montepython/sampler.py", line 44, in run
    mcmc.chain(cosmo, data, command_line)
  File "/SUVEDHA/montepython_public-master/montepython/mcmc.py", line 330, in chain
    Cholesky = la.cholesky(C).T
  File "/home/suvedha/.conda/envs/MP/lib/python2.7/site-packages/scipy/linalg/decomp_cholesky.py", line 91, in cholesky
    check_finite=check_finite)
  File "/home/suvedha/.conda/envs/MP/lib/python2.7/site-packages/scipy/linalg/decomp_cholesky.py", line 40, in _cholesky
    "definite" % info)
numpy.linalg.linalg.LinAlgError: 3-th leading minor of the array is not positive definite `

Thanks in advance
Suvedha

**Comment by brinckmann** [comment]
Hi Suvedha,

Are you still having this problem? Can you give me some more information on what you were trying to do?

It looks like the covmat was not positive definite, which might come from an unfortunate covmat computation based on e.g. a small number of points, in which case my best guess is to try to again and hope the code doesn't update the covmat so early. You can try to adjust the flag --update <int>, which sets the number of steps between attempted covmat updates.

Best,
Thejs

**Comment by SuvedhaNaik** [comment]
Hi Thejs, 

Thanks for your reply. I did try again for a longer chain and that didn't cause any problem. I'm using --update 50 now.

Thanks again,
Suvedha
