### ISSUE TITLE
ValueError while analayzing chains

### ISSUE THREAD

**Issue by SuvedhaNaik** [brinckmann/montepython_public#72]
Hello All. 

I recently encountered below mentioned error several times while analyzing the chains. I could obtain the covariance matrix till 100000 * 20 chains. After few steps, the program stopped. I restarted the chain using
`mpiexec.hydra -n 20 montepython/MontePython.py -o chains/Feature_31-08-19/ -r chains/Feature_31-08-19/2019-09-03_150000__1.txt -b chains/Feature_31-08-19/Feature_31-08-19.bestfit -c chains/Feature_31-08-19/Feature_31-08-19.covmat --update 50 -N 20000 `

Still, not able to analyze.

Output:

Running Monte Python v3.2.0

--> Scanning file chains/Feature_31-08-19/2019-09-06_170000__18.txt : Removed 16479 non-markovian points, 9 points of burn-in, keep 21266 steps
                                          2019-09-06_170000__15.txt : Removed 15876 non-markovian points, 3 points of burn-in, keep 19996 steps
                                          2019-09-06_170000__8.txt  : Removed 16549 non-markovian points, 15 points of burn-in, keep 20183 steps
                                          2019-09-06_170000__5.txt  : Removed 16913 non-markovian points, 104 points of burn-in, keep 20094 steps
                                          2019-09-06_170000__6.txt  : Removed 16666 non-markovian points, 32 points of burn-in, keep 20424 steps
                                          2019-09-06_170000__20.txt : Removed 16422 non-markovian points, 0 points of burn-in, keep 20104 steps
                                          2019-09-06_170000__12.txt : Removed 16155 non-markovian points, 17 points of burn-in, keep 20333 steps
                                          2019-09-06_170000__1.txt  : Removed 16278 non-markovian points, 0 points of burn-in, keep 20364 steps
                                          2019-09-06_170000__14.txt : Removed 16810 non-markovian points, 25 points of burn-in, keep 20160 steps
                                          2019-09-06_170000__4.txt 
Traceback (most recent call last):
  File "montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/SUVEDHA/montepython_public-3.2/montepython/run.py", line 31, in run
    custom_command)
  File "/SUVEDHA/montepython_public-3.2/montepython/run.py", line 190, in safe_initialisation
    cosmo, data, command_line, success = initialise(custom_command)
  File "/SUVEDHA/montepython_public-3.2/montepython/initialise.py", line 58, in initialise
    analyze(command_line)
  File "/SUVEDHA/montepython_public-3.2/montepython/analyze.py", line 92, in analyze
    convergence(info)
  File "/SUVEDHA/montepython_public-3.2/montepython/analyze.py", line 268, in convergence
    spam = remove_bad_points(info)
  File "/SUVEDHA/montepython_public-3.2/montepython/analyze.py", line 1769, in remove_bad_points
    for line in ifilterfalse(iscomment,f)]))
ValueError: could not convert string to float: 

Any input would be helpful.
Thanks
Suvedha

**Comment by SuvedhaNaik** [comment]
Hello,

Thanks for the quick reply.  The file looks fine. I have attached the same for reference.
[Feature_31-08-19.log](https://github.com/brinckmann/montepython_public/files/3583707/Feature_31-08-19.log)
[2019-09-06_170000__4.txt](https://github.com/brinckmann/montepython_public/files/3583708/2019-09-06_170000__4.txt)

**Comment by brinckmann** [comment]
Hi,

My hotel wifi isn't good enough to download the chains file, but another thought I had is maybe you're running out of memory while analyzing the chains? If you're analyzing on a cluster try to increase the number of OMP processes, e.g.
export OMP_NUM_THREADS=8

Best,
Thejs

**Comment by SuvedhaNaik** [comment]
Hi, 

I had 20 chains of which 9 chains are giving me the ValueError. If I exclude them while analyzing, I'm getting the posterior pdf. However, I could not find any unusual lines in those chains. 

Thanks,
Suvedha

**Comment by brinckmann** [comment]
Hi,

Yeah I suspect the problem is that's a lot of chains and they're all very long. Try to analyze only 
`python montepython/MontePython.py info 2019-09-06_170000__1*`
I.e. half of your chains. If this works I'm willing to bet it's a memory issue! The solution would then be to use a machine or configuration with more memory to analyze (e.g. by using more cores with openMP).

Best,
Thejs

**Comment by SuvedhaNaik** [comment]
Hi, 

I tried what you suggested. Still few of them gave the same problem. Here's the output:

Running Monte Python v3.2.0

--> Scanning file chains/Feature_31-08-19/2019-09-06_170000__18.txt : Removed 16479 non-markovian points, 9 points of burn-in, keep 25742 steps
                                          2019-09-06_170000__15.txt : Removed 15876 non-markovian points, 3 points of burn-in, keep 24529 steps
                                          2019-09-06_170000__12.txt : Removed 16155 non-markovian points, 17 points of burn-in, keep 24813 steps
                                          2019-09-06_170000__1.txt  : Removed 16278 non-markovian points, 0 points of burn-in, keep 24793 steps
                                          2019-09-06_170000__14.txt : Removed 16810 non-markovian points, 25 points of burn-in, keep 24517 steps
                                          2019-09-06_170000__16.txt : Removed 16158 non-markovian points, 108 points of burn-in, keep 24611 steps
                                          2019-09-06_170000__10.txt
Traceback (most recent call last):
  File "montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/SUVEDHA/montepython_public-3.2/montepython/run.py", line 31, in run
    custom_command)
  File "/SUVEDHA/montepython_public-3.2/montepython/run.py", line 190, in safe_initialisation
    cosmo, data, command_line, success = initialise(custom_command)
  File "/SUVEDHA/montepython_public-3.2/montepython/initialise.py", line 58, in initialise
    analyze(command_line)
  File "/SUVEDHA/montepython_public-3.2/montepython/analyze.py", line 92, in analyze
    convergence(info)
  File "/SUVEDHA/montepython_public-3.2/montepython/analyze.py", line 268, in convergence
    spam = remove_bad_points(info)
  File "/SUVEDHA/montepython_public-3.2/montepython/analyze.py", line 1769, in remove_bad_points
    for line in ifilterfalse(iscomment,f)]))
ValueError: could not convert string to float: 


Thank You, 
Suvedha

**Comment by brinckmann** [comment]
Hi Suvedha,

Can you please zip the chains directory and email it (or a link to it) to me? I'll try to analyze it locally and see if I can figure out what's going on.

Best,
Thejs

**Comment by SuvedhaNaik** [comment]
Hi, 

Regarding the issue I posted above, I have something to update.

I initially started my MontePython run with 20 chains of 50k steps each. Then I tried to go for 100k steps using the **restart** command. But I was unable to do that because of the ValueError I mentioned above.

However, I tried to do it in a different way and it seemed to be working without throwing any error. But I'm not sure whether this is equivalent to restart command or not. Here are the steps I did. 

i. I initially ran MontePython for 20 chains 50 k each
ii. I analyzed all of them (with --want-covmat) to get a .bestfit and .covmat files
iii. I started another MontePython run (20 chains 50k each) in a different directory with log.param, .bestfit, .covmat files obtained in (ii) as input.
iv. Then I analyzed these chains which converged with convergence ratio <0.01

Any input would be helpful. 

P.S.: I'm trying to constrain 2 additional parameter in the matter power spectrum. The posterior PDF of the parameters I added, are not Gaussian. Therefore, the 2D PDF has no distinct 1sigma and 2 sigma contours.

Thanks in advance, 
Suvedha
