### ISSUE TITLE
Numpy compatibility

### ISSUE THREAD

**Issue by anirbandas89** [brinckmann/montepython_public#88]
Hi,

I was trying to run montepython3 for the first time (I've used v2 before). I'm getting the following error:

RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
Traceback (most recent call last):
  File "../montepython/MontePython.py", line 13, in <module>
    from run import run
  File "/user1/anirban/DM_annihilation/montepython_public-3.2/montepython/run.py", line 7, in <module>
    from initialise import initialise
  File "/user1/anirban/DM_annihilation/montepython_public-3.2/montepython/initialise.py", line 9, in <module>
    from data import Data
  File "/user1/anirban/DM_annihilation/montepython_public-3.2/montepython/data.py", line 18, in <module>
    from scipy.optimize import fsolve
  File "/apps/Python/anaconda2/lib/python2.7/site-packages/scipy/optimize/__init__.py", line 232, in <module>
    from .optimize import *
  File "/apps/Python/anaconda2/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 37, in <module>
    from .linesearch import (line_search_wolfe1, line_search_wolfe2,
  File "/apps/Python/anaconda2/lib/python2.7/site-packages/scipy/optimize/linesearch.py", line 18, in <module>
    from scipy.optimize import minpack2
ImportError: numpy.core.multiarray failed to import

It looks like a numpy version issue, but I checked my numpy version is 1.11.3 which should be fine accrding to readme. I'd appreciate any help. 

I've provided the path for python 2.7 in MontePython.py.

Thanks,
Anirban

**Comment by dchooper** [comment]
Hi,

Are you still getting this issue with the latest MontePython version? 

Best,
Deanna

**Comment by anirbandas89** [comment]
No, it's resolved.
